on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup visual studio
        uses: microsoft/setup-msbuild@v2

      - name: Install winget
        uses: Cyberboss/install-winget@v1

      - name: Install LLVM
        run:
          winget install --id=LLVM.LLVM -e

      - name: Test shell
        run: |
          get-command cl
