on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup visual studio
        uses: microsoft/setup-msbuild@v2

      - name: Install winget and LLVM
        run: |
          # https://github.com/asheroto/winget-install 
          Install-Script winget-install -Force -RequiredVersion 5.0.5
          winget-install -Force
          winget source update
          winget install --id LLVM.LLVM -e

      - name: Test shell
        run: |
          get-command clang
          get-command flang
